### ISSUE TITLE
[Arr] flatten works unintuitive for lists

### ISSUE THREAD

**Issue by veewee** [azjezz/psl#113]
**Describe the bug**
`Arr\flatten()` uses the index of the array to flatten it. This is ok for maps, but strange for lists:

**To Reproduce**
```php
flatten([[1, 2, 3], [4, 5, 6]]);
```

Expected: [1, 2, 3, 4, 5, 6]
Actual: [4, 5, 6]

**Additional context**

Maybe we could make it behave more like the JS version for lists?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

**Comment by azjezz** [comment]
Hm, actually, I don't really consider this a bug, as the function signature doesn't promote the use of `list`, but instead `array<Tk, Tv>`, i think what would be a better alternative is having another namespace that deals with lists, what do you think about adding `Psl\Vec\flatten`? 🤔

**Comment by veewee** [comment]
That might make sense, but will also result in yet another duplication of a lot of existing`Arr|Iter` functions.
It would make the psalm typing easier though :)

**Comment by azjezz** [comment]
I'm introducing new `Vec` and `Dict` components next week, all functions in `Arr` will be deprecated and moved to either `Dict` or `Vec` depending on what they deal with ( v1.3.0 ), v2.0.0 will not contain `Arr`.

**Comment by azjezz** [comment]
this is done :)

use `Vec\concat` to concat multiple lists, `Dict\flatten` to flatten multiple dicts :D
