### ISSUE TITLE
PHP 5.6 Support

### ISSUE THREAD

**Issue by mholubowski** [azjezz/psl#131]
**Is your feature request related to a problem? Please describe.**
For some of our important projects, we need to use PHP 5.6 for comparability with the customers' environments. 

**Describe the solution you'd like**
Any information on what it would take to use psl within a PHP 5.6 project. 

**Describe alternatives you've considered**
Writing some of the functions we need ourselves over time. This library is much better. 

Thank you to the creators and maintainers of psl.

**Comment by azjezz** [comment]
I'm sorry @mholubowski, but PSL only supports PHP 7.4 >=, and there's no plans to support old PHP releases.
