### ISSUE TITLE
support for non-empty-array/non-empty-list

### ISSUE THREAD

**Issue by bendavies** [azjezz/psl#145]
Hi there!

**Is your feature request related to a problem? Please describe.**

Is is feasible to 
1. add `non-empty-array` and `non-empty-list` support to the type system, such that:
1. the return  `Psl\Iter\first` and other functions can be `T` and not `T|null`?

**Describe the solution you'd like**
I want to be able to do things like:

```php
<?php

declare(strict_types=1);

use Psl;

class FooExtractor
{
    /** @param list<Foo> $foos */
    public function __invoke(array $foos): Foo
    {
        $foosFiltered = Vec\filter(
            $foos,
            function (Foo $foo): bool {
                ...
            }
        );

        //assert $foosFiltered type is non-empty-list/array here.

        //this will error as the return type is `T|null`
        return Iter\first($foosFiltered);
    }
}
```

Is there a better way to achieve what I'm trying to do?

Thanks!

**Comment by azjezz** [comment]
hm, we used to have `Arr\firstx` and `Arr\lastx` at some point, but i don't remember when they were removed.

the solution here is, if there's a function that returns `T|null`; we should add a function with the same name, but suffixed with `x` that always return `T`, and throws `Psl\Exception\InvariantViolationException` in case of `null`

e.g:

```hack
namespace Psl\Iter;

use Psl;
use Psl\Vec;

function firstx<T>(iterable<T> $iterable): T
{
  $vec = Vec\values<T>($iterable);
  Psl\invariant(contains_key($vec, 0), 'Expected $iterable to contain at least 1 element.');

  return $vec[0];
}
```

If you would like to open a PR adding `Iter\firstx`, and `Iter\lastx`, that would be great :)

**Comment by azjezz** [comment]
*actually* there's a better solution to this.

instead of:

```php
/**
 * @template T
 * @param iterable<T> $iterable
 * @return T|null
 */
function first(iterable $iterable) { ... }
```

we can have:

```php
/**
 * @template T
 * @param iterable<T> $iterable
 * @return ($required is true ? T : (T|null))
 */
function first(iterable $iterable, bool $required = false) { ... }
```

This would be a better solution in the long run, which we can adopt in other components such as `Str` ( e.g: `Str\before`, `Str\after` ).

and when you are sure `$iterable` is not empty, you can do `Iter\first($iterable, required: true)`

**Comment by azjezz** [comment]
issue moved to the plugin repository,
