### ISSUE TITLE
move psalm plugin to a seperate package

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#166]
psalm plugin should be moved to it's own repository ( https://github.com/php-standard-library/psalm-plugin )

TODO:

- [x] move the plugin to it's own repository and change the namespace to `Psl\Psalm` ( instead of `Psl\Integration\Psl` )
- [x] deprecate the current plugin and recommend installing the package instead.
- [ ] remove the plugin located in this repository in v2.0

**Comment by veewee** [comment]
Why should it be a separate package?

**Comment by azjezz** [comment]
to drop psalm from dev dependency in this project, and use the phar instead.

the reason to drop psalm: https://github.com/azjezz/psl/tree/asio/src/Psl/Asio/Internal#amphp-event-loop

**Comment by azjezz** [comment]
not sure if we would use the phar, or have a dedicated directory to install dev tools, either way, we can't keep it in require-dev
