### ISSUE TITLE
Performance of reimplemented functions?

### ISSUE THREAD

**Issue by ghost** [azjezz/psl#167]
I understand that a completely reimplemented function in userland code will be slower than the compiled C counterpart, yet I thought that for many functions PSL simply implemented a wrapper for native functions, thus having little overhead.

I got a little surprised when I was replacing some instances of `\array_unique` of suddenly getting a measurable drop in performance (those are rather large arrays, but that's what I get).

[Here](https://phpsandbox.io/n/shrill-wood-lolj-cehre) I can replicate it with this code:

```php
$arr = [];
$iterations   = 10;
$array_size   = 1000;
$random_range = 5000;

for ($i = 0; $i < $array_size; $i++) {
    $arr[] = Psl\SecureRandom\int(0, $random_range);
}

$total = 0;
$ta0 = microtime(true);
for ($e = 0; $e < $iterations; $e++) {
    $total += \count(\array_unique($arr));
}
$ta1 = microtime(true);

echo "Native\n";
echo $total / $iterations, "\n";
echo 'Time: ' . round($ta1 - $ta0, 4), "\n\n";

$total = 0;
$ta0   = microtime(true);
for ($e = 0; $e < $iterations; $e++) {
    $total += \Psl\Iter\count(\Psl\Dict\unique($arr));
}
$ta1 = microtime(true);

echo "Psl\n";
echo $total / $iterations, "\n";
echo 'Time: ' . round($ta1 - $ta0, 4);
```

The result in this case is 0.0009 seconds for native implementations, against 0.0841 seconds for using Psl. True, for this case 0,08 seconds is still something I can live with, but it's still a very marked cost increase. For my particular use case can even become problematic.

Is this what's expected, or I'm using the library incorrectly? Mind, this is not in no way a complaint, I love the library even if this is a tradeoff to be aware of, but just wanted to be sure this was not me "holding it wrong".

**Comment by azjezz** [comment]
this is expected, if you are using PHP >= 7.4, i recommend including `vendor/azjezz/psl/src/preload.php` in your preload file, or using it as a preload file if you don't have anything else to preload, which should give better performance as functions will be cached after the first run ( assuming you are using php-fpm or fastcgi ), if it's a CLI script, i cannot recommand anything that would improve performance here.

**Comment by azjezz** [comment]
Hm, after https://phpsandbox.io/n/wispy-leaf-75nn-pnldg, i noticed that the unqiue function is causing the performance issue here, not `count` ( which has almost the same performance ).

I think there's a way to fix this.

in https://github.com/azjezz/psl/blob/1.6.x/src/Psl/Dict/unique.php#L17, we should add
```
if (is_array($iterable)) {
  return array_unique($iterable);
}
```

can you please send a PR and verify that performance has been improved in this case specifically? 

P.S: any pull request to improve performance is welcome, even if it adds complexity.

**Comment by ghost** [comment]
Just tried the fix and now the performance is perfectly comparable.

PR incoming.

![image](https://user-images.githubusercontent.com/60233442/112437159-eee2cc00-8d46-11eb-83eb-77b33fe16bec.png)

Thanks!
