### ISSUE TITLE
Vec\sum()?

### ISSUE THREAD

**Issue by yivi** [azjezz/psl#186]
I see that there is no `array_sum()` equivalent provided.

Is this intentional, or is something that you'd be willing to consider?

**Comment by yivi** [comment]
F*ck. Mislabelled "bug".

**Comment by azjezz** [comment]
This function already exist as `Math\sum` ( https://github.com/azjezz/psl/blob/1.7.x/src/Psl/Math/sum.php#L14 ), or are you looking for a different behavior?

**Comment by azjezz** [comment]
there's also https://github.com/azjezz/psl/blob/1.7.x/src/Psl/Math/sum_floats.php#L14 for floats :)

**Comment by yivi** [comment]
Thanks! I was looking in the wrong place, following "core" "logic" for this.
