### ISSUE TITLE
strict types is ignored when mapping or filtering arrays due to the usage of PHP builtin functions

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#194]
This bug was introduced in #169 by mistake, the solution would be to wrap all callbacks provided by the end user in another closure to ensure that strict types is used.

**Environment (please complete the following information):**
 - OS: *
 - PHP version: 7.4, 8.0
 - Version: 1.6, 1.7

**Additional context**

see https://github.com/Roave/BackwardCompatibilityCheck/pull/306#discussion_r635004153

**Comment by azjezz** [comment]
we have to benchmark which solution is better:

1. wrap callbacks in a closure
2. re-implement array_* functions in userland.

**Comment by Ocramius** [comment]
> re-implement array_* functions in userland.

I think we'll likely need to suck it up and keep using `array_` functions here: assuming 100% type coverage on sources, we can assume that the given values are within the type boundaries of the provided callbacks.

The `array_*` functions are massively outperforming any iterative approach, as they can operate at zval level.

**Comment by azjezz** [comment]
fixed and released as 1.6.1 and 1.7.1
