### ISSUE TITLE
Introduce benchmark + performance regression checks

### ISSUE THREAD

**Issue by Ocramius** [azjezz/psl#195]
As `Psl\` grows in size and adoption, its performance becomes one important evaluation point when considering it for downstream adoption.

This question came up in both https://github.com/azjezz/psl/issues/194 and https://github.com/Roave/BackwardCompatibilityCheck/pull/306, and it would be a good idea to have reference/comparison.

The idea is to have following benchmarks:

 * comparison of Psl and internal functions or constructs it replaces (assuming 100% type coverage and no runtime errors occur)
 * comparison of Psl against itself at different releases

For that, it would be interesting to use https://github.com/phpbench/phpbench/tree/1.0.1

@dantleech do you know if there is a sensible way to run benchmarks and compare them in CI? That's something that is kinda missing within PHPBench' docs :thinking:

**Comment by azjezz** [comment]
some functions will always be slower than core ( e.g: [`Regex\matches`](https://github.com/azjezz/psl/blob/1.8.x/src/Psl/Regex/matches.php#L19) will always perform worst than preg_match, due to additional error handling ), the question is how much difference is considered acceptable.

**Comment by Ocramius** [comment]
Obviously, Psl will always be slower than core: it is required to keep the baseline under control though, as performance regressions often go unnoticed.

Also, knowing how much slower the library is allows for downstream consumers to take an informed decision as to when/where to use it.

**Comment by dantleech** [comment]
r.e. running in CI - I'm doing this with a [bash script](https://github.com/phpactor/worse-reflection/blob/master/.github/phpbench_regression_test.sh) with assertions at a tolerance of 10% (but this is too optimistic, 15% might be better). It's still an experimental area (i also tried two separate actions to combine their results, but this doesn't work as the actions can run in completely different envs I guess).

**Comment by Ocramius** [comment]
Sounds feasible - even with a very high tolerance, it's more about looking at it before releasing, I guess?

Intra-worker performance should be relatively stable

**Comment by dantleech** [comment]
> it's more about looking at it before releasing, I guess?

with a 15% tolerance it should catch obvious regressions, I guess if you want to check more subtly then before release/at PR time.

> Intra-worker performance should be relatively stable

as in 2 actions? at least for me (the one time i tried it) this resulted in less stable results

**Comment by Ocramius** [comment]
> as in 2 actions? at least for me (the one time i tried it) this resulted in less stable results

No no, same action and container: nothing guarantees that you will get two boxes running on a similar hardware otherwise.
