### ISSUE TITLE
Filesystem - read_file - InvariantViolationException message should contains filename

### ISSUE THREAD

**Issue by vaclavvanik** [azjezz/psl#204]
**Is your feature request related to a problem? Please describe.**

When I try to `read_file` which does not exist,  is not file or is not readable `InvariantViolationException` is thrown with message like `$file does not exist`.

I would like to see given filename in exception message. It's than easier to debug and fix possible problem.

**Describe the solution you'd like**

Replace 

```php
Psl\invariant(exists($file), '$file does not exist.');
```

with

```php
Psl\invariant(exists($file), Str\format('File "%s" does not exist.', $file));
```

Thrown `RuntimeException` contains provided `$file` too.

**Comment by azjezz** [comment]
I'm pretty sure this is done in multiple other places as well.

would you like to send a PR? :)

**Comment by vaclavvanik** [comment]
Sure, I will create PR. Which branch should I target?

**Comment by azjezz** [comment]
1.8.x since it's not a bug :)

**Comment by azjezz** [comment]
Note: instead of Psl\invariant($fact, Str\format($message, ...$args)); you should do Psl\invariant($fact, $message, ...$args); ( the message will be formatted only if the $fact is false.
