### ISSUE TITLE
shape() with oneOf()?

### ISSUE THREAD

**Issue by temp** [azjezz/psl#207]
Type checking with shape() works like a charm! 👍 

But we stumbled upon some checks that we didn't know how to solve.
Something like React PropTypes oneOf() would be nice (https://reactjs.org/docs/typechecking-with-proptypes.html).
Or is there a combination of PSL methods that is able to achieve this?

```php

use Psl\Type;

$data = [
  ['status' => 'A'],
  ['status' => 'B'],
  ['status' => 'A'],
  ['status' => 'C'],
];

$type = Type\vec(Type\shape([
  'status' => Type\oneOf(['A', 'B'])
]))
$type->assert($data);
```

We implemented our own Type Check for this, but it would be awesome to have this out of the box.

**Comment by azjezz** [comment]
what is the difference between this and Type\union(Type\literal_scalar('A'), Type\literal_scalar('B')); ? 

```php
use Psl\Type;

$data = [
  ['status' => 'A'],
  ['status' => 'B'],
  ['status' => 'A'],
  ['status' => 'C'],
];

$type = Type\vec(Type\shape([
  'status' => Type\union(Type\literal_scalar('A'), Type\literal_scalar('B'))
]))
$type->assert($data);
```

**Comment by temp** [comment]
Nothing, I guess - that's what er where looking for. I find it rather hard to find solutions for non-trivial cases. Although you might argue that this IS a trivial case :-D
Nevertheless, thanks!

**Comment by azjezz** [comment]
No problem :) glad i could help.
