### ISSUE TITLE
Typing for `shape` makes psalm think it's a no-op

### ISSUE THREAD

**Issue by zerkms** [azjezz/psl#212]
**Describe the bug**
I'm not sure if it's Psl typing or psalm-related bug, so trying it here first :-)

**To Reproduce**
```php
    private function augment(array $data): array
    {
        $data2 = Type\shape([
            'meta' => Type\dict(Type\array_key(), Type\mixed()),
        ], true)->assert($data);

        $data2['meta']['id'] = 42;

        return $data2;
    }

    /**
     * @param mixed $data
     */
    private function augment2($data): array
    {
        $data2 = Type\shape([
            'meta' => Type\dict(Type\array_key(), Type\mixed()),
        ], true)->assert($data);

        $data2['meta']['id'] = 42;

        return $data2;
    }
```
This code emits just one error
```
ERROR: RedundantCondition - filename.php:96:19 - Type array<array-key, mixed> for $data is always array (see https://psalm.dev/122)
        ], true)->assert($data);
```
and it refers to the `augment` function. It only fails type check if it's already known to be an array, but not when `mixed`.

**Expected behavior**
I think in both cases there should be no type check warnings.

**Environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu] N/a
 - PHP version 7.4
 - Version 1.6.1

**Additional context**

**Comment by azjezz** [comment]
are you using the psl psalm plugin ( github.com/php-standard-library/psalm-plugin )? 🤔

**Comment by zerkms** [comment]
Sure, if it's not easily reproducible for you I can make up a repro repository tomorrow.

**Comment by azjezz** [comment]
what psalm version are you using exactly? could you please send a PR containing a failing static analysis test? ( see: https://github.com/azjezz/psl/tree/1.8.x/tests/static-analysis/Type ), this will be easier for me to debug.

**Comment by zerkms** [comment]
@azjezz just done it https://github.com/azjezz/psl/pull/214

Presumably, that problem is masked with suppressing `RedundantCondition`.

I understand the reason `RedundantCondition` is used (to have extra runtime checks), but why isn't it suppressed in place: like in cases when you know it for sure, so can tell it explicitly, instead of suppressing it everywhere and masking real issues?

That question is valid to all suppressions as well: would it be better to only suppress in-place so that it didn't accidentally mask real unexpected problems?

**Comment by azjezz** [comment]
> That question is valid to all suppressions as well: would it be better to only suppress in-place so that it didn't accidentally mask real unexpected problems?

I think yes, I'm just lazy 😛

**Comment by zerkms** [comment]
@azjezz would you be in favour of that change? To clean up `psalm.xml` and entirely remove all global suppressions?

**Comment by azjezz** [comment]
ref: https://github.com/vimeo/psalm/issues/6573

**Comment by azjezz** [comment]
same as #227; closing.
