### ISSUE TITLE
Redundant shuffling in Iter\random()

### ISSUE THREAD

**Issue by zerkms** [azjezz/psl#213]
**Describe the bug**
I believe there is no need to shuffle given a random index is selected anyway.

**To Reproduce**
https://github.com/azjezz/psl/blob/9aef574325bdf854c4886ad0006c4886b0b88842/src/Psl/Iter/random.php#L23-L42

**Expected behavior**
Should not shuffle before picking a random element.

**Environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - PHP version [e.g. 7.4, 8.0]

**Additional context**

**Comment by azjezz** [comment]
I don't think this is a "bug", as the behavior is still what you would expect ( i.e random value ), but we can remove the shuffling in the next minor release 👍

**Comment by zerkms** [comment]
Indeed not a bug, the other options fit even worse though :-D

**Comment by azjezz** [comment]
fixed in https://github.com/azjezz/psl/commit/6f5c992f4054ad08449cd170d18060d4e5c620b6
