### ISSUE TITLE
asserting type of non_empty_string triggers psalm error when asserting known string

### ISSUE THREAD

**Issue by bendavies** [azjezz/psl#227]
**Describe the bug**
Psalm reports a string is always a string here, but we are checking for a non empty string.
How can I avoid this error?

**To Reproduce**
```php
<?php

use Psl\SecureRandom;
use Psl\Type;

$prefix = SecureRandom\string(SecureRandom\int(0, 1));

Psl\Invariant(
    !Type\non_empty_string()->matches($prefix),
    'string is empty!',
);
```

```
ERROR: TypeDoesNotContainType - test.php:8:1 - Type string for $prefix is always string (see https://psalm.dev/056)
Psl\Invariant(
```

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - PHP version 8.0
 - `vimeo/psalm:4.10.0`
 - `azjezz/psl:1.8.0`

**Additional context**

**Comment by bendavies** [comment]
@azjezz any ideas here?

**Comment by azjezz** [comment]
Hm, i'm taking a look at this, weird thing, when the return type is a TypeInterface<non-empty-string>, it fails, but when it's NonEmptyStringType, it doesn't 🤔 

https://psalm.dev/r/68932ca73c

vs

https://psalm.dev/r/8ecfbcc96a

**Comment by bendavies** [comment]
strange!

**Comment by azjezz** [comment]
ref: https://github.com/vimeo/psalm/issues/6573

**Comment by azjezz** [comment]
since this is a psalm issue, i'm closing it here.
