### ISSUE TITLE
DateTime API

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#27]

**Comment by bendavies** [comment]
@azjezz I was just looking to see if PSL had a datetime api! any plans for this?

**Comment by azjezz** [comment]
not yet, the plan would probably be to port HSL datetime once it is stable.

see: https://github.com/hhvm/hsl-experimental/pull/180/ https://github.com/hhvm/hsl-experimental/pull/182/ https://github.com/hhvm/hsl-experimental/pull/183

**Comment by bendavies** [comment]
@azjezz good to know, thanks!

**Comment by lexidor** [comment]
I thought I'd chime in, as I have stuck with the hsl. The incomplete implementation of DateTime in hsl-experimental hasn't been touched in a while. The last time I have heard anyone mention it in the hhvm sphere was in 2022. The project hsl-experimental will be archived in on Oct 1st, 2023.

 > _not yet, the plan would probably be to port HSL datetime once it is stable._

Waiting for a stable DateTime API to emerge in the hsl would be... ill-advised. Go ahead a forge your own path.

**Comment by azjezz** [comment]
> Waiting for a stable DateTime API to emerge in the hsl would be... ill-advised. Go ahead a forge your own path.

I have already figured since development has stopped there, I have a branch locally for a DateTime API, but it needs a bit of clean up and more testing before i can push it, not sure if i have the time to do that currently.
