### ISSUE TITLE
Uncaught RuntimeException on Psl\Iter\Iterator::current() 

### ISSUE THREAD

**Issue by pottink** [azjezz/psl#288]
**Describe the bug**
When running tests I get following error:

```
PHP Fatal error:  During inheritance of Iterator: Uncaught RuntimeException: PHP Error: Return type of Psl\Iter\Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Iter/Iterator.php:90 in phar:///home/runner/work/http-tools/http-tools/tools/psalm.phar/src/Psalm/Internal/ErrorHandler.php:53
Stack trace:
#0 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Iter/Iterator.php(18): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Internal/Loader.php(683): require_once('...')
#2 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Internal/Loader.php(690): Psl\Internal\Loader::load()
#3 [internal function]: Psl\Internal\Loader::Psl\Internal\{closure}()
#4 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Internal/Loader.php(750): class_exists()
#5 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Internal/Loader.php(675): Psl\Internal\Loader::loadClasses()
#6 /home/runner/work/http-tools/http-tools/vendor/azjezz/psl/src/Psl/Internal/Loader.php(699): Psl\Internal\Loader::Psl\Internal\{closure}()
```

**To Reproduce**
[GitHub Actions:
](https://github.com/phpro/http-tools/runs/4333028876?check_suite_focus=true)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - PHP: 8.1
 - Version: 1.6.0

**Comment by azjezz** [comment]
>  - Locking azjezz/psl (1.6.0)
> https://github.com/phpro/http-tools/runs/4333028876?check_suite_focus=true#step:7:9

PSL 1.6.0 doesn't support PHP 8.1, i suggest you explicitly require PSL ^1.9.1

**Comment by azjezz** [comment]
Hmm, phppro/http-tools requires PHP 7.4, so you can't actually upgrade to PSL 1.9.1 yet, i think we can back port the PHP 8.1 fix to all branch from 1.6 to 1.8, and release a new version for each, this way you can set minimum required PSL version in your project to `1.6.1`.

**Comment by veewee** [comment]
No worries, we are planning to drop 7.4 support since they can still use older versions of the package with 7.4.
The issue why this was not clear, is because we are validating --prefer-lowest with --ignore-platform-reqs I suppose.

Thanks!

**Comment by azjezz** [comment]
> is because we are validating --prefer-lowest with --ignore-platform-reqs I suppose.

not really, 1.6 allows php ^7.4 || ^8.0, meaning PHP 8.1 is fine, and 1.6 being the last version to support 7.4, i think it would be okay to back port PHP 8.1 fixes there ( using the attribute, since we can't use mixed return type there )

**Comment by azjezz** [comment]
ref: https://github.com/azjezz/psl/commit/9fdb771b1d04e57b7ad82fe01a367a37075e47d2

**Comment by pottink** [comment]
Sorry, version is 1.9.2, typo.

**Comment by azjezz** [comment]
> version is 1.9.2

no, i changed the version in your issue.

You are using --prefer-lowest in GitHub Action, which installs PSL 1.6.0.

**Comment by azjezz** [comment]
@veewee i'll leave this up to you, as i don't think i will have time to work on it personally in next couple of days ( i believe you have permission necessary to do so and release 1.6.2, 1.7.4, and 1.8.2 )

i personally think it's a good idea to fix compatibility with 8.1 for ^1.6.x since it's the last version with PHP 7.4 support, so people wanting to support PHP 7.4 and upwards can do so.

**Comment by veewee** [comment]
Sounds like a solid plan! I am also very limited in time for a while. We'll see who gets to it first.

**Comment by azjezz** [comment]
fixed :)

released:

- https://github.com/azjezz/psl/releases/tag/1.6.2 ( probably what you want to use )
- https://github.com/azjezz/psl/releases/tag/1.7.4
- https://github.com/azjezz/psl/releases/tag/1.8.2
