### ISSUE TITLE
Writing to a non existing file using \Psl\File\WriteMode::TRUNCATE does not create the file

### ISSUE THREAD

**Issue by dragosprotung** [azjezz/psl#351]
**Describe the bug**
Writing to a non existing file using `\Psl\File\WriteMode::TRUNCATE` does not create the file.
As per the documentation:
```php
/**
 * Open for writing only; place the file pointer at the beginning of the
 * file and truncate the file to zero length. If the file does not exist,
 * attempt to create it.
 */
case TRUNCATE = 'wb';
```

**To Reproduce**
```php
\Psl\File\write('non-existing-file.txt', 'Hello!', mode: \Psl\File\WriteMode::TRUNCATE); // throws \Psl\File\Exception\NotFoundException
```

**Expected behavior**
File to be created

**Additional context**
Is the documentation wrong or the implementation ?

I can create a PR for this, but I would like to know if we should change the behaiviour (possible BC break?) or maybe introduce a new write mode

**Comment by azjezz** [comment]
This is indeed a bug.

https://github.com/azjezz/psl/blob/9b7517dcbacd07ec807bf45179bf72c7372516cf/src/Psl/File/WriteHandle.php#L31-L40

`$open_or_create = $write_mode === WriteMode::OPEN_OR_CREATE;` should be `$open_or_create = $write_mode === WriteMode::OPEN_OR_CREATE || $write_mode === WriteMode::TRUNCATE;`
