### ISSUE TITLE
assert/coerce on dict will always loop over entire dict

### ISSUE THREAD

**Issue by BackEndTea** [azjezz/psl#359]
**Is your feature request related to a problem? Please describe.**

In some cases i just want to check that a value i get is a dict.
Now i write something like this:

```php
use Psl\Type;

$value =  Type\dict(Type\mixed(), Type\mixed())->assert($value);
```

The downside is that this will loop over the entire dict. 

**Describe the solution you'd like**
Either a new type that describes an dict with keys and values, which does not need to loop over every item.
Or a check in the `Dict` class that returns early if both keys and values are mixed

**Describe alternatives you've considered**
Take the performance hit or do a check myself.

**Comment by azjezz** [comment]
I don't really see a safe of way of doing this in rhe existing dict/vec types, i think introducing Type\mixed_dict and Type\mixed_vec is the way to go about it.
