### ISSUE TITLE
Idea: `Psl\Type\enum(MyEnum::class)`

### ISSUE THREAD

**Issue by Ocramius** [azjezz/psl#366]
I was working on a way to convert inputs to `enum` instances.

## My own janky implementation

On an old application (pre-PHP 8.1), I had my own abstraction for ENUMs, based on [`myclabs/enum`](https://github.com/myclabs/php-enum).

I built a `MyEnum::pslType()` abstraction, which produces a `\Psl\Type\TypeInterface<static>` (`static` being `MyEnum`):

```php
class MyEnum extends Enum
{
    // ...

    /** @return \Psl\Type\TypeInterface<static> */
    public static function pslType(): \Psl\Type\TypeInterface
    {
        return new class (static::class) extends \Psl\Type\Type
        {
            /** @param class-string<MyEnum> $className */
            public function __construct(private string $className)
            {
            }

            public function coerce(mixed $value)
            {
                if ($value instanceof $this->className) {
                    return $value;
                }

                $type = \Psl\Type\union(
                    ...array_map(
                        static fn (mixed $value): \Psl\Type\TypeInterface => \Psl\Type\literal_scalar($value),
                        array_values(($this->className)::toArray())
                    )
                )->withTrace($this->getTrace());

                return ($this->className)::from($type->coerce($value));
            }

            public function assert(mixed $value)
            {
                if ($value instanceof $this->className) {
                    return $value;
                }

                throw AssertException::withValue($value, $this->toString(), $this->getTrace());
            }

            public function toString(): string
            {
                return $this->className;
            }
        };
    }
``` 

It's really ugly, but it works.

## Providing ENUM support in PSL itself?

Since ENUMs are now a built-in concept of the language, I was wondering if we could provide a `Psl\Type\enum()` function which:

 * has a strict `assert()`
 * has a strict `matches()`
 * attempts to produce an `enum` instance in `coerce()`

**Comment by azjezz** [comment]
Yes, i think adding enum support in Type component is needed at this point, hopefully the next minor version of PSL will be ready by next week which will include this one.

**Comment by Ocramius** [comment]
BTW, not expecting you to write one: was just throwing it in the bucket.

It is easily built in userland, at this stage, just very (very!) inefficient, plus the errors don't work well with the rest of the type component.
