### ISSUE TITLE
`Psl\Filesystem\exists()` has an invalid `@psalm-assert-if-true`

### ISSUE THREAD

**Issue by Ocramius** [azjezz/psl#370]
https://github.com/azjezz/psl/blob/82f241ea8ad997701e2fdcd130e8a9433eeaeafa/src/Psl/Filesystem/exists.php#L9-L17

In this declaration, `@psalm-assert-if-true` seems to be misplaced.

In the case where a `non-empty-string` is given in, `vimeo/psalm:5.0.0` fails with:

```
All possible types for this return were invalidated - This may be dead code (see https://psalm.dev/179)
```

An example:

https://psalm.dev/r/3031def44f

```php
<?php

/** @psalm-assert-if-true non-empty-string $bar */
function foo(string $bar): bool {
    return $bar === 'irrelevant';
}

$value = 'hello';

if (foo($value)) {
    return 'ok';
}

return $value;
```

Now... Psalm is obviously confused here too, but the assertion is also misplaced, since the input may already have been declared as a `non-empty-string` by the caller here.

**Comment by azjezz** [comment]
The assertion has already been removed from PSL 2.3.0 released earlier today with support for Psalm* 5.0

**Comment by Ocramius** [comment]
Dayum that was fast 🤣

**Comment by azjezz** [comment]
Thanks to @veewee :D i have been too busy with Rust to even notice psalm v5 🤣

**Comment by veewee** [comment]
The real issue here is psalm indeed: https://github.com/vimeo/psalm/issues/8659
