### ISSUE TITLE
Undeprecate `positive_int`

### ISSUE THREAD

**Issue by dragosprotung** [azjezz/psl#399]
**Is your feature request related to a problem? Please describe.**
`positive_int` means `int<1, max>`
`uint` means `int<0, max>`

I think we should keep `positive_int` because it represents a different type.
There is not alternative to represent `positive-int` (for example like an intersection).
Using `uint` instead of `positive_int` means manual checks to see if the value is also `0`

**Describe the solution you'd like**
Do not deprecate `positive_int`

**Comment by azjezz** [comment]
yea, i realized this was a mistake but forgot to do it 😅 can you send a PR for it? I'll release 2.4.1 right after.

we should also add `@ara-return TypeInterface<0|uint>` to `positive_int()`

**Comment by dragosprotung** [comment]
Here you go: #400
