### ISSUE TITLE
base64 url safe encoding

### ISSUE THREAD

**Issue by Gashmob** [azjezz/psl#407]
**Is your feature request related to a problem? Please describe.**
For the implementation of WebAuthn in a web app, I need to send a key id in the uri. So I use base64 encoding for that. But following the [rfc](https://www.rfc-editor.org/rfc/rfc4648) the encoding uses + and / characters which are not really safe for an uri. Section 5 of rfc describe an url version of encoding using - and _ characters. Is it possible to implement it inside psl?

**Describe the solution you'd like**
It will be nice to have functions like this:
```php
function encodeUrl(string $binary): string;

function decodeUrl(string $base64): string;
```

**Describe alternatives you've considered**
Currently, as a workaround I'm doing that:
```php
strtr(encode($key_id), '+/', '-_');
```

**Comment by azjezz** [comment]
I'm okay with adding two new functions to `Psl\Encoding\Base64`, or a new `Psl\Encoding\Base64\Url` sub-component.

a PR would be welcome.


```php
use Psl;
use Psl\Encoding\Base64;

$data = '...';

$encoded = Base64\url_encode($data);
$decoded = Base64\url_decode($encoded);

Psl\invariant($data === $decoded, 'expected $decoded to be the same as $data');
```

or


```php
use Psl;
use Psl\Encoding\Base64\Url;

$data = '...';

$encoded = Url\encode($data);
$decoded = Url\decode($encoded);

Psl\invariant($data === $decoded, 'expected $decoded to be the same as $data');
```
