### ISSUE TITLE
`CoercionException::withValue()` called but not throwed. Is this dead code?

### ISSUE THREAD

**Issue by devnix** [azjezz/psl#411]
https://github.com/azjezz/psl/blob/62632502a7a2004601ebdfa06b32eff6a33a042e/src/Psl/Type/Internal/PositiveIntType.php#L56-L59

The tests are passing, as the code continues until line 70

https://github.com/azjezz/psl/blob/62632502a7a2004601ebdfa06b32eff6a33a042e/src/Psl/Type/Internal/PositiveIntType.php#L70

Does it make sense to keep that `if`?

**Comment by veewee** [comment]
Well spotted! I've provided a PR for this.
The tests pass cause of line 70 indeed, yet we can skip some if checks to speed up the coercion process.
