### ISSUE TITLE
intersection + shapes unexpected behaviour (possible bug?)

### ISSUE THREAD

**Issue by asgrim** [azjezz/psl#424]
Hey folks, I'm trying to work out if it is possible to intersect two shapes in `azjezz/psl` ? I'm doing the following:

```
        $type = T\intersection(
            T\shape([
                'key1' => T\string(),
            ]),
            T\shape([
                'key2' => T\int(),
            ])
        );
        /** @psalm-trace $type */
        $coerced = $type->coerce($unknownType);
        /** @psalm-trace $coerced */
        return $coerced;
```

(see https://github.com/asgrim/psl-shape-intersection-test/blob/main/src/Test.php#L24 )

But the output (seen on https://github.com/asgrim/psl-shape-intersection-test ) doesn't seem to indicate that something (`azjezz/psl`? `php-standard-library/psalm-plugin`?) understands the intersection properly:

```
ERROR: Trace
at /home/james/workspace/me/psl-shape-intersection-test/src/Test.php:24:9
$type: Psl\Type\TypeInterface<array{key1: string}> (see https://psalm.dev/224)
        /** @psalm-trace $type */
        $coerced = $type->coerce($unknownType);


ERROR: Trace
at /home/james/workspace/me/psl-shape-intersection-test/src/Test.php:26:9
$coerced: array{key1: string} (see https://psalm.dev/224)
        /** @psalm-trace $coerced */
        return $coerced;


ERROR: InvalidReturnStatement
at /home/james/workspace/me/psl-shape-intersection-test/src/Test.php:26:16
The inferred type 'array{key1: string}' does not match the declared return type 'array{key1: string, key2: int}' for PslShapeIntersectionTest\Test::coerceArray (see https://psalm.dev/128)
        return $coerced; 
```

I would expect `$coerced` to be `array{key1: string, key2: int}` here, but something seems to have missed off the second part of the intersection.

Does anyone have any ideas here? :thinking:

**Comment by azjezz** [comment]
shape function doesn't allow extra keys by default, so it would fail.

can you try enabling extra keys in both types?

**Comment by asgrim** [comment]
> can you try enabling extra keys in both types?

enabling `allow_unknown_fields` on both the shapes does not appear to affect anything here :/

**Comment by veewee** [comment]
I assume the issue lies at psalm level:
https://psalm.dev/r/910181f147

It seems like you cannot intersect 2 generic shapes properly and it falls back to the first provided shape:

```
INFO: [Trace](https://psalm.dev/224) - 16:25 - $res: array{a: 'a'}
```

**Comment by asgrim** [comment]
Yeah - I think you're right; checking into Psalm's, there's [a bunch of potential issues](https://github.com/vimeo/psalm/issues?page=1&q=is%3Aissue+is%3Aopen+intersection) relating to array intersections; not sure exactly which one is right :grin: Likely an upstream thing then. Thank you so much!
