### ISSUE TITLE
Type\implements_interface

### ISSUE THREAD

**Issue by zerkms** [azjezz/psl#432]
**Is your feature request related to a problem? Please describe.**
There is a `Assert::implementsInterface($className, $interface)` method that is implemented as 

```php
    /**
     * @psalm-pure
     * @psalm-template ExpectedType of object
     * @psalm-param class-string<ExpectedType> $interface
     * @psalm-assert class-string<ExpectedType> $value
     *
     * @param mixed  $value
     * @param mixed  $interface
     * @param string $message
     *
     * @throws InvalidArgumentException
     */
    public static function implementsInterface($value, $interface, $message = '')
    {
        if (!\in_array($interface, \class_implements($value))) {
            static::reportInvalidArgument(\sprintf(
                $message ?: 'Expected an implementation of %2$s. Got: %s',
                static::valueToString($value),
                static::valueToString($interface)
            ));
        }
    }
```

`Psl\invariant` solution for the similar problem (to check whether a class name implements an interface) does not provide the same psalm type assertion still.

**Describe the solution you'd like**

```php
Type\implements_interface($interface)->asset($className);
```

**Describe alternatives you've considered**
`Psl\invariant`, but it does not narrow the type.

**Additional context**

Happy to provide a PR :-)

**Comment by veewee** [comment]
Hello,

Thanks for reporting!

Maybe a `Type\class_string($optionalType)` would be a better way to go here?

That way you could:

```php

class_string()->assert(stdClass::class);
class_string(stdClass::class)->assert(stdClass::class);
class_string(SomeInterface::class)->assert(SomeImplementation::class);
```

Which is closer to how psalm checks the types as well. Making it quite easy to get the types right:

https://psalm.dev/r/c7c481754b


Internally, it could:

* Assert with [class_exists](https://www.php.net/manual/en/function.class-exists.php) on the provided type (without autoloading?).
  * is_a always checks if the class exists  so might be overkill: https://3v4l.org/C8bmR
* Assert with the [is_a](https://www.php.net/manual/en/function.is-a.php) function if a type was provided.

For `coerce`, it could apply the same rules and throw a `CoercionException` if the rules don't apply - similar to the `instance_of` type.

What do you think?

A PR is welcome of course 😉

**Comment by zerkms** [comment]
`Type\class_string` is a good name indeed, I like it more than what I suggested.

> without autoloading?

and yes, just from the top of my head I think it should **not** trigger autoloading.

**Comment by zerkms** [comment]
I'm not a psalm expert, but I believe it won't be possible to create a single `ClassNameType` that provides both `class-name` and `class-name<T>` because its declaration would then look like this:

```php
/**
 * @template T
 *
 * @extends (T is null ? Type<class-string> : Type<class-string<T>>)
 *
 * @internal
 */
final class ClassStringType extends Type
```

and that `@extends` is marked as invalid:

```
ERROR: InvalidDocblock - ../src/Psl/Type/Internal/ClassStringType.php:18:1 - @template-extends has invalid class (T is null ? Psl\Type\Type<class-string> : Psl\Type\Type<class-string<T:Psl\Type\Internal\ClassStringType as object>>) (see https://psalm.dev/008)
```

After giving another think I also realised that I cannot think of a use case when assertion just for `class-name` would be helpful.
