### ISSUE TITLE
Corece an `array` out of an `stdClass`?

### ISSUE THREAD

**Issue by Ocramius** [azjezz/psl#436]
Just throwing out ideas, but in the context of JSON -> Domain, the `ShapeType` could be useful when dealing with JSON structures where the difference between hashmap and array is sometimes to be preserved:

```php
$input = <<<'JSON'
{
  "foo": "hello world!"
}
JSON;

$data = Json\decode($input, false);

echo Type\shape([
    'foo' => Type\non_empty_string(),
])->coerce($data)['foo'];
```

**Comment by veewee** [comment]
This could be a nice addition indeed.

Just thinking out loud here: We could accept any `object` and cast it to an `array`.

https://3v4l.org/Hrv0H
```php
<?php

$x = (object) [];
$x->foo = 'bar';


class X {
    public $foo = 'bar';
    private $baz = 'bar';
}



var_dump((array) $x);
var_dump((array) new X);
```

However:

* I'm not sure that this will work for all kind of objects. Maybe you know about this?
* It takes all properties, also private ones.
* It seems a bit hacky to implement it this way.
  * The alternative is to use reflection ([like this](https://github.com/veewee/reflecta/blob/main/src/Reflect/properties_get.php)) - but this package does not have a reflection component ([yet](https://github.com/azjezz/psl/discussions/402)).

**Comment by Ocramius** [comment]
> We could accept any `object`

IMO a bit too risky 😁

Array casts on objects lead to weird null byte keys too.

My endorsement would be to start with `stdClass`, since its semantics are well known.

Any `Traversable` is also already handled.

**Comment by Ocramius** [comment]
https://github.com/azjezz/psl/pull/437
