### ISSUE TITLE
Is nonnull helpful in any way?

### ISSUE THREAD

**Issue by zerkms** [azjezz/psl#473]
**Describe the bug**

```php
        /** @var null|int $v */
        $v = 5;

        /** @psalm-trace $v */;

        $v2 = Type\nonnull()->assert($v);

        /** @psalm-trace $v2 */;
```

```
ERROR: Trace - f.php:50:31 - $v: int|null (see https://psalm.dev/224)
        /** @psalm-trace $v */;


ERROR: MixedAssignment - f.php:52:9 - Unable to determine the type that $v2 is being assigned to (see https://psalm.dev/032)
        $v2 = Type\nonnull()->assert($v);


ERROR: Trace - f.php:54:32 - $v2: mixed (see https://psalm.dev/224)
        /** @psalm-trace $v2 */;
```

So, what's the point to have it at all?

**To Reproduce**
Code to reproduce the behavior:

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu]
 - PHP version [e.g. 7.4, 8.0]

**Additional context**

**Comment by veewee** [comment]
@zerkms 
This is recently fixed through https://github.com/azjezz/psl/pull/465
We are working on the release of v3 which will contain this improvement.

I'dd say it's rather a limitation of psalm than this package though ;)
