### ISSUE TITLE
NonNullType has been moved, but Loader is referencing to a old place

### ISSUE THREAD

**Issue by phpjob** [azjezz/psl#487]
**Describe the bug**
- We upgraded from version ^2.9.0 to 3.0.0 and got an error in the console.
```

PHP Warning:  PHP Startup: Failed to open stream: No such file or directory in /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php on line 943
PHP Fatal error:  Uncaught Error: Failed opening required '/home/vendor/azjezz/psl/src/Psl/Type/Internal/NonNullType.php' (include_path='.:/usr/local/lib/php') in /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php:943
Stack trace:
#0 //vendor/azjezz/psl/src/Psl/Internal/Loader.php(954): Psl\Internal\Loader::load('Psl/Type/Intern...')
#1 [internal function]: Psl\Internal\Loader::Psl\Internal\{closure}('Psl\\Type\\NonNul...')
#2 /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php(1011): class_exists('Psl\\Type\\NonNul...')
#3 /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php(936): Psl\Internal\Loader::loadClasses()
#4 /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php(960): Psl\Internal\Loader::Psl\Internal\{closure}()
#5 /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php(932): Psl\Internal\Loader::autoload(Object(Closure))
#6 /home/vendor/azjezz/psl/src/preload.php(9): Psl\Internal\Loader::preload()
#7 /home/config/preload.php(7): require('/home/vend...')
#8 {main}
  thrown in /home/vendor/azjezz/psl/src/Psl/Internal/Loader.php on line 943

```

In commit https://github.com/azjezz/psl/commits/d68cd6be64a1fe7355fc02669cc6fa6440294799/src/Psl/Type/NonNullType.php
and PR https://github.com/azjezz/psl/pull/478 the type has been moved into the global "namespace".
But in the Loader only the namespace was updated, not the path. The loader has still a reference to a non existing file yet -> https://github.com/azjezz/psl/blob/3.0.0/src/Psl/Internal/Loader.php#L711C56-L711C67

A deep look 

**Expected behavior**
NonNullType is loaded from the correct place. 

`Psl\\Type\\NonNullType' => 'Psl/Type/Internal/NonNullType.php',` -> `Psl\\Type\\NonNullType' => 'Psl/Type/NonNullType.php',`

**Environment (please complete the following information):**
 - PHP version 8.3
 - Version 3.0.0

**Additional context**

**Comment by veewee** [comment]
Thanks for reporting and fixing!
It's released under https://github.com/azjezz/psl/releases/tag/3.0.1
