### ISSUE TITLE
Loader is referencing to Interval.php, which is not existing

### ISSUE THREAD

**Issue by phpjob** [azjezz/psl#489]
**Describe the bug**
In 
https://github.com/azjezz/psl/pull/446/files#diff-6c05f0262aafb9c91c79fdca36fe8a2d683cd6388a0b1921310b83f1b4caf27aR855
`3.0.0` `'Psl\\DateTime\\Duration' => 'Psl/DateTime/Interval.php',` was introduced.

But the file does not exist (https://github.com/azjezz/psl/tree/3.0.1/src/Psl/DateTime). I could create a PR, but not sure if this was a mistake or the plan was to reference to a different file.
Currently this causing errors.

**Environment (please complete the following information):**
 - PHP version 8,2
 - Version 3.0.1

**Comment by veewee** [comment]
Hello @phpjob,

Thanks for reporting.
There is indeed no duration class.

This seems the way to go to me:

```diff
-        'Psl\\DateTime\\Duration' => 'Psl/DateTime/Interval.php',
+        'Psl\\DateTime\\Duration' => 'Psl/DateTime/Duration.php',
```

Can you create a PR?
Can you spot any other additional issues whilst preloading?

**Comment by phpjob** [comment]
@veewee Sure, I'll have a look this evening. 👍 . Thanks for the quick response.
