### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by veewee** [azjezz/psl#52]
Hello,

Today I landed on this repository. It looks very similar with something I am creating:
https://github.com/veewee/happy-helpers

Feel free to check it out.

There are:

* many simalar approaches: iterables, predicates, ...
* some other approaches like: results
* some additional things like xml, dom, callables, ...

Besides what is in there, I also put some thought in stuff like file resources, but nothing concrete.

My intention of that package was mostly learning, but I am using it in some of my private projects and would love to introduce a far more advanced version in customer projects. I was not planning of putting a lot of extra features in there at the moment.

Since this package is very in-line with wath I am doing and since it is far more mature, I'dd be willing to merge/donate them to this project.

Let me know if you are interested! We can always have a chat if you're up to it.

**Comment by azjezz** [comment]
Hello @veewee, I'm very interested in this, and would love to bring some things over from happy-helpers.

I'm taking a look at your repository currently and I'll send you a DM with my findings on twitter :)
