### ISSUE TITLE
XML API

### ISSUE THREAD

**Issue by veewee** [azjezz/psl#60]

**Comment by veewee** [comment]
@azjezz 
Knowing that I implemented pretty much everything XML related in https://github.com/veewee/xml instead now., how do you want to continue with this issue?

Since I know you don't really like the DOM part, I am willing to move it over to the php-standard-library organisation and maintain it in there as well, if that might be a solution for you. I think the other components turned out quite good, but feel free to propose improvements.

**Comment by azjezz** [comment]
not sure really, i assigned it to you since you are much more familiar with it.

i think we want to have something to do with `DOM` in here, but we don't want to also dive deep into the XML rabbit hole.

so we can have a replacement for `DOMDocument`, but not the other parts or xml ( we can refer people to `veewee/xml` if they need more advanced features ).

WDYT?

**Comment by veewee** [comment]
The dom extension is the worst to wrap, since it's api is so broad. That is why I went with a more flexible design in veewee/Xml: leaking parts of the dom objects to the end user whilst keeping in control about the more error-prone parts.

I dont really know how to simplify it for this package's standards / point of view.

For this package a xml_encode and xml_decode function could be nice. But I already wrote that for veewee/xml and it's quite some logic to get everything parsed safely.

So i'dd just recommend using that one instead :p

**Comment by azjezz** [comment]
If you think it would be too much to wrap DOM here, i think we can close the issue then, and agree to delegate things to `veewee/xml`, we don't have to dig deep into html/xml stuff, for html ( #140 ), we just need `encode`/`decode` functions ( same as PHPs `htmlspecialchars` )

**Comment by veewee** [comment]
Ok. Closing this one for now.
