### ISSUE TITLE
[Iter] split `reduce` into multiple functions

### ISSUE THREAD

**Issue by veewee** [azjezz/psl#73]
Currently the `Iter\reduce` function acts as a `reduce_with_keys`. Is there a specific reason for this or is it safe to split it into `reduce`, `reduce_keys` and `reduce_with_keys` function?

https://github.com/azjezz/psl/blob/develop/src/Psl/Iter/reduce.php

**Comment by azjezz** [comment]
You are right, I think we should split this.
