### ISSUE TITLE
[Str] add `after` and `before` helpers

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#75]
add `after{_ci|_last{_ci}}` and `before{_ci|_last{_ci}}` helper string functions.

We should implement these functions for `Psl\Str`, `Psl\Str\Byte`, and `Psl\Str\Grapheme` ( refs #74 ), which totals to a new 24 functions.

`Psl\Str` implementations would have an extra argument `?string $encoding = null`.

```php
function after(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function after_ci(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function after_last(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function after_last_ci(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function before(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function before_ci(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function before_last(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;

function before_last_ci(string $haystack, string $needle, bool $include_needle = false, int $offset = 0): string;
```

**Comment by khamer** [comment]
I'm not sure what `after` and `before` are supposed to do, to be honest. Is the idea that

- `Str\after('hello world', 'w') === 'orld'`
- `Str\after('hello world', 'w', true) === 'world'`
- `Str\after('hello world', 'w', true, 2) === 'rld'`
- `Str\after('hello world', 'w', false, 2) === 'ld'`
- `Str\before('hello world', 'o') === 'hell'`
- `Str\before('hello world', 'o', true) === 'hello'`
- `Str\before('hello world', 'o', true, 2) === 'hello w'`
- `Str\before('hello world', 'o', false, 2) === 'hello '`

I understand based on hack that `_last` would indicate using the last occurrence of `$needle` in `$haystack` and `_ci` indicates case insensitive, but wasn't sure if I understood how you wanted after/before to work, and whether the offset was used as a length of to offset from `$needle` or what.

**Comment by azjezz** [comment]
your understanding is correct, but `$offset` is not used as a length, but as an `$offset` since these functions would use `search`, `search_last`, `search_ci`, and `search_last_ci` internally, the `$offset` argument should be passed to the search function.

see: after, afterLast, before, and beforeLast at https://github.com/symfony/string/blob/master/AbstractString.php#L130
